/* DaggWorld Portfolio — original interactions + current professional updates */
(() => {
  'use strict';
  const ready = (fn) => document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', fn, { once: true }) : fn();
  ready(() => {
    const preloader = document.getElementById('preloader');
    if (preloader) setTimeout(() => preloader.classList.add('hidden'), 700);
    if (window.AOS) AOS.init({ duration: 800, once: true, offset: 50, easing: 'ease-out-cubic', disable: () => window.innerWidth < 768 });

    const typed = document.getElementById('typed-text');
    if (typed && window.Typed) new Typed('#typed-text', { strings: ['Freelance Software Developer','Full Stack Developer','IT Systems Builder','Networking & ICT Specialist','Cybersecurity Enthusiast','AI Explorer'], typeSpeed:52, backSpeed:32, backDelay:1700, loop:true, showCursor:true, cursorChar:'|' });

    const heroDescription = document.querySelector('.hero-description');
    if (heroDescription) heroDescription.innerHTML = 'Final-year BSc Information Technology student at North-West University and a <strong>freelance technology professional</strong>. I build software, websites, business systems and practical ICT solutions — including work delivered for <strong>real clients</strong> through freelance projects and THAMAS TECH WORLD.';
    const aboutIntro = document.querySelector('.about-intro');
    if (aboutIntro) aboutIntro.innerHTML = 'I am a <strong>final-year BSc Information Technology</strong> student at <strong>North-West University</strong> and a <strong>freelance software and IT professional</strong>. My work combines software development, networking, databases, information security, AI-assisted tools and practical business technology.';
    const aboutParagraphs = document.querySelectorAll('#about .about-content > p');
    if (aboutParagraphs[1]) aboutParagraphs[1].textContent = 'Beyond university projects, I have already worked on real client requirements — translating business needs into websites, systems, networking solutions and technical support. I enjoy taking a problem from an idea through development, testing and delivery.';
    if (aboutParagraphs[2]) aboutParagraphs[2].textContent = 'I continue to grow through hands-on freelance work, personal products and client projects. My goal is to build technology that is useful, maintainable and understandable to the people who depend on it.';

    const stats = document.querySelectorAll('.stat-number'), labels = document.querySelectorAll('.stat-label');
    const statData = [['10+','Projects Built'],['45+','Technologies & Tools'],['15+','GitHub Repositories'],['Client','Real Client Work']];
    statData.forEach((item,i)=>{ if(stats[i]){stats[i].dataset.count=item[0]==='Client'?'1':parseInt(item[0],10);stats[i].textContent=item[0]} if(labels[i])labels[i].textContent=item[1] });

    document.querySelectorAll('.project-card').forEach(card=>{if(/CruizeControl|Car Rental|Rental Cars/i.test(card.textContent))card.remove()});
    const projectGrid = document.querySelector('.projects-grid');
    if(projectGrid){
      const projects=[
        {title:'Centalytics — Hospital Management System',type:'Full Stack · Healthcare',image:'assets/images/hospital.png',alt:'Centalytics hospital management system',description:'A healthcare management platform for structured patient records, appointments, doctors, visits, prescriptions, laboratory workflows and role-based dashboards.',tech:['HTML5','CSS3','JavaScript','Firebase'],repo:'https://github.com/Dagg12/Centalytics',live:'https://centalytics-cef6c.web.app'},
        {title:'DaggWorld Business OS',type:'Product · Business Systems',image:'https://raw.githubusercontent.com/Dagg12/daggworld-business-os/main/public/assets/daggworld-system-preview.png',alt:'DaggWorld Business OS',description:'A practical business operating system designed to help small businesses organise customers, records, operations, analytics and day-to-day digital workflows.',tech:['React','JavaScript','Firebase','Business Analytics'],repo:'https://github.com/Dagg12/daggworld-business-os',live:'https://daggworld-business-toolkit.web.app/'},
        {title:'The Ranger — Safari Management System',type:'ASP.NET · MySQL',image:'https://github.com/Dagg12/Ranger-Management-Sytem/raw/master/The%20ranger%20images/landing%20page%20.png',alt:'The Ranger safari management system landing page',description:'A safari/private-reserve management system covering clients, owners, accommodation, game drives and bookings, with reporting and operational workflows.',tech:['ASP.NET Web Forms','C#','MySQL'],repo:'https://github.com/Dagg12/Ranger-Management-Sytem',live:''},
        {title:'THAMAS TECH WORLD — Business Website',type:'Client · ICT & Networking',image:'assets/images/thamas-portfolio.png',alt:'THAMAS TECH WORLD business website',description:'A business website representing real-world ICT and networking services, including WiFi solutions, computer support, websites and technical services.',tech:['HTML5','CSS3','JavaScript','GSAP'],repo:'https://github.com/Dagg12/Thamas-portfolio',live:'https://dagg12.github.io/Thamas-portfolio/'},
        {title:'M&M / Fragrance House Website',type:'Freelance · Client Web',image:'assets/images/portfolio.png',alt:'Client website project',description:'A client-focused web experience built to present a product brand online with a polished visual identity, responsive layout and clear calls to action.',tech:['HTML5','CSS3','JavaScript'],repo:'https://github.com/Dagg12/Philippine-website/',live:'https://dagg12.github.io/Philippine-website/'},
        {title:'Clinical Blood Bank System',type:'ASP.NET · Database',image:'assets/images/bloodbank.png',alt:'Clinical Blood Bank system',description:'A blood-bank management application for donor records, blood inventory, hospital requests and stock tracking.',tech:['C#','ASP.NET','MySQL'],repo:'https://github.com/TeeCee07/ClinicalBloodBank',live:''},
        {title:'Personal Portfolio Website',type:'Web · Personal Brand',image:'assets/images/portfolio.png',alt:'Vhukhudo Kevin Thamaga portfolio website',description:'This portfolio: a responsive personal brand site combining software projects, education, experience, technical skills and professional contact channels.',tech:['HTML5','CSS3','JavaScript'],repo:'https://github.com/Dagg12/Portfolio-Website',live:'https://dagg12.github.io/Portfolio-Website/'}
      ];
      projectGrid.innerHTML=projects.map((p,i)=>`<article class="project-card d12-current-project" data-aos="flip-up" data-aos-delay="${Math.min(i*60,300)}"><div class="project-card-inner"><div class="project-image"><img src="${p.image}" alt="${p.alt}" loading="lazy" onerror="this.src='assets/images/portfolio.png'" /><div class="project-overlay"><span class="project-type">${p.type}</span></div></div><div class="project-content"><h3 class="project-title">${p.title}</h3><p class="project-description">${p.description}</p><div class="project-tech">${p.tech.map(t=>`<span>${t}</span>`).join('')}</div><div class="project-links"><a href="${p.repo}" target="_blank" rel="noopener noreferrer" class="project-link github-link"><i class="fab fa-github"></i> Code</a>${p.live?`<a href="${p.live}" target="_blank" rel="noopener noreferrer" class="project-link demo-link"><i class="fas fa-external-link-alt"></i> Live Demo</a>`:''}</div></div></div></article>`).join('');
    }

    const timeline=document.querySelector('#experience .timeline');
    if(timeline) timeline.innerHTML=`<div class="timeline-item" data-aos="fade-up"><div class="timeline-dot"><i class="fas fa-laptop-code"></i></div><div class="timeline-content"><div class="timeline-header"><h3 class="timeline-title">Freelance Software Developer & IT Specialist</h3><span class="timeline-date">2024 – Present</span></div><h4 class="timeline-company">Independent Freelance Work</h4><ul class="timeline-list"><li><i class="fas fa-check-circle"></i> Delivered websites and digital systems for real clients.</li><li><i class="fas fa-check-circle"></i> Gathered client requirements and translated them into practical technology solutions.</li><li><i class="fas fa-check-circle"></i> Built and maintained responsive websites and business-focused applications.</li><li><i class="fas fa-check-circle"></i> Provided technical support, troubleshooting and IT consulting.</li></ul></div></div><div class="timeline-item" data-aos="fade-up" data-aos-delay="100"><div class="timeline-dot"><i class="fas fa-network-wired"></i></div><div class="timeline-content"><div class="timeline-header"><h3 class="timeline-title">Co-Founder · Networking & ICT Specialist</h3><span class="timeline-date">2026 – Present</span></div><h4 class="timeline-company"><a href="https://dagg12.github.io/Thamas-portfolio/" target="_blank" rel="noopener noreferrer">THAMAS TECH WORLD <i class="fas fa-external-link-alt"></i></a></h4><ul class="timeline-list"><li><i class="fas fa-check-circle"></i> WiFi installation, configuration, coverage improvement and network troubleshooting.</li><li><i class="fas fa-check-circle"></i> Computer repairs and hardware troubleshooting.</li><li><i class="fas fa-check-circle"></i> Website development and digital business support.</li><li><i class="fas fa-check-circle"></i> Delivered practical ICT solutions for customers and households.</li></ul></div></div>`;

    if(!document.getElementById('daggworld-store')){const store=document.createElement('section');store.id='daggworld-store';store.className='section d12-store-section';store.innerHTML=`<div class="container"><div class="section-header" data-aos="fade-up"><span class="section-tag">DaggWorld</span><h2 class="section-title">Digital <span class="highlight">Store</span></h2><div class="section-divider"></div></div><div class="d12-store-card" data-aos="fade-up"><div class="d12-store-image"><img src="assets/images/store.png" alt="DaggWorld digital store" loading="lazy" onerror="this.src='https://raw.githubusercontent.com/Dagg12/daggworld-business-os/main/public/assets/daggworld-system-preview.png'" /></div><div class="d12-store-copy"><span class="section-tag">DAGGWORLD DIGITAL PRODUCTS</span><h3>Small Business Digital Starter Kit</h3><p>Practical digital resources created to help small businesses get organised, improve their online presence and work more professionally.</p><div class="d12-store-actions"><a class="btn btn-primary" href="https://payhip.com/b/5uo72" target="_blank" rel="noopener noreferrer"><i class="fas fa-store"></i> Visit Store</a><a class="btn btn-outline" href="https://payhip.com/DaggWorld" target="_blank" rel="noopener noreferrer">Explore DaggWorld</a></div></div></div></div>`;document.querySelector('#contact')?.before(store)}

    const contactSection=document.querySelector('#contact');if(contactSection){const phone=contactSection.querySelector('a[href^="tel:"]');if(phone)phone.textContent='+27 67 846 8311';}

    const style=document.createElement('style');style.textContent=`.d12-current-project{min-height:100%}.d12-current-project .project-image img{object-fit:cover;object-position:center}.d12-current-project .project-description{min-height:96px}.d12-store-section{position:relative;overflow:hidden}.d12-store-card{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(0,.95fr);gap:34px;align-items:center;padding:28px;border:1px solid rgba(148,163,184,.25);border-radius:28px;background:rgba(15,23,42,.72);backdrop-filter:blur(14px);box-shadow:0 24px 70px rgba(0,0,0,.2)}.d12-store-image{border-radius:20px;overflow:hidden;min-height:280px;background:#0f172a;display:flex;align-items:center;justify-content:center}.d12-store-image img{width:100%;height:100%;min-height:280px;object-fit:cover}.d12-store-copy h3{font-size:clamp(1.7rem,3vw,2.5rem);margin:.65rem 0 1rem}.d12-store-copy p{color:var(--text-secondary,#94a3b8);line-height:1.8}.d12-store-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:22px}@media(max-width:800px){.d12-store-card{grid-template-columns:1fr;padding:18px}.d12-store-image,.d12-store-image img{min-height:220px}.d12-current-project .project-description{min-height:0}}`;document.head.appendChild(style);

    document.querySelectorAll('.matrix-background').forEach(canvas=>{const ctx=canvas.getContext('2d');if(!ctx)return;let drops=[];const chars='01<>/{}[]ABCDEFGHIJKLMNOPQRSTUVWXYZ';const resize=()=>{const r=canvas.parentElement.getBoundingClientRect();canvas.width=r.width;canvas.height=r.height;drops=Array.from({length:Math.max(1,Math.floor(r.width/18))},()=>Math.random()*-30)};const draw=()=>{ctx.fillStyle='rgba(10,15,26,.08)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='16px monospace';ctx.fillStyle='rgba(37,99,235,.35)';drops.forEach((d,i)=>{ctx.fillText(chars[Math.floor(Math.random()*chars.length)],i*18,d*18);drops[i]=d+.45;if(d*18>canvas.height&&Math.random()>.97)drops[i]=0});requestAnimationFrame(draw)};resize();draw();window.addEventListener('resize',resize,{passive:true})});

    const navbar=document.getElementById('navbar'),progress=document.getElementById('scrollProgress'),top=document.getElementById('backToTop');window.addEventListener('scroll',()=>{navbar?.classList.toggle('scrolled',window.scrollY>50);if(progress)progress.style.width=`${Math.min(100,(window.scrollY/(document.documentElement.scrollHeight-window.innerHeight))*100)}%`;top?.classList.toggle('visible',window.scrollY>400)},{passive:true});top?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
    const hamburger=document.getElementById('hamburger'),navLinks=document.getElementById('navLinks');if(hamburger&&navLinks){hamburger.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');hamburger.classList.toggle('active',open);hamburger.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')))}
    const themeToggle=document.getElementById('themeToggle');if(themeToggle){const icon=themeToggle.querySelector('i'),saved=localStorage.getItem('theme')||'dark';document.documentElement.setAttribute('data-theme',saved);if(icon)icon.className=saved==='dark'?'fas fa-sun':'fas fa-moon';themeToggle.addEventListener('click',()=>{const next=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);localStorage.setItem('theme',next);if(icon)icon.className=next==='dark'?'fas fa-sun':'fas fa-moon'})}
    document.querySelectorAll('.skill-progress').forEach(bar=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){bar.style.width=(bar.dataset.width||0)+'%';io.disconnect()}}),{threshold:.3});io.observe(bar)});
    document.querySelectorAll('.stat-number').forEach(el=>{if(el.textContent==='Client')return;const target=parseInt(el.dataset.count,10);if(!target)return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let n=0;const timer=setInterval(()=>{n+=Math.max(1,Math.ceil(target/40));if(n>=target){n=target;clearInterval(timer)}el.textContent=n+'+'},25);io.disconnect()}}),{threshold:.5});io.observe(el)});
    const sections=[...document.querySelectorAll('section[id]')],links=[...document.querySelectorAll('.nav-links a')];const updateActive=()=>{let current='';sections.forEach(s=>{if(window.scrollY>=s.offsetTop-140)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${current}`))};window.addEventListener('scroll',updateActive,{passive:true});updateActive();const year=document.getElementById('currentYear');if(year)year.textContent=new Date().getFullYear();
    if(window.innerWidth>=1024){const c=document.getElementById('customCursor'),d=document.getElementById('customCursorDot');let x=0,y=0,cx=0,cy=0,dx=0,dy=0;document.addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY});const loop=()=>{cx+=(x-cx)*.1;cy+=(y-cy)*.1;dx+=(x-dx)*.2;dy+=(y-dy)*.2;if(c){c.style.left=cx+'px';c.style.top=cy+'px'}if(d){d.style.left=dx+'px';d.style.top=dy+'px'}requestAnimationFrame(loop)};loop();document.addEventListener('mouseover',e=>{if(e.target.closest('a,button,.project-card,.skill-category,.contact-card')){c?.classList.add('active');d?.classList.add('active')}});document.addEventListener('mouseout',e=>{if(e.target.closest('a,button,.project-card,.skill-category,.contact-card')){c?.classList.remove('active');d?.classList.remove('active')}})}
  });
})();
