/* DaggWorld Portfolio — current content + verified project artwork */
(() => {
  'use strict';
  const ready = fn => document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', fn, { once: true }) : fn();
  ready(() => {
    const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
    $('#preloader') && setTimeout(() => $('#preloader').classList.add('hidden'), 700);
    if (window.AOS) AOS.init({duration:800, once:true, offset:50, easing:'ease-out-cubic', disable:()=>innerWidth<768});
    if ($('#typed-text') && window.Typed) new Typed('#typed-text',{strings:['Freelance Software Developer','Full Stack Developer','IT Systems Builder','Networking & ICT Specialist','Cybersecurity Enthusiast','AI Explorer'],typeSpeed:52,backSpeed:32,backDelay:1700,loop:true,showCursor:true,cursorChar:'|'});
    if ($('.hero-description')) $('.hero-description').innerHTML='Final-year BSc Information Technology student at <strong>North-West University</strong> and a <strong>freelance technology professional</strong>. I build software, websites, business systems and practical ICT solutions for real-world requirements.';
    if ($('.about-intro')) $('.about-intro').innerHTML='I am a <strong>final-year BSc Information Technology</strong> student and <strong>freelance software and IT professional</strong>. My work spans software development, networking, databases, information security, AI-assisted tools and practical business technology.';
    const ap=$$('#about .about-content > p'); if(ap[1]) ap[1].textContent='Beyond university projects, I have worked on real client requirements — translating business needs into websites, systems, networking solutions and technical support.'; if(ap[2]) ap[2].textContent='I continue to grow through freelance work, personal products and client projects, with a focus on useful, maintainable and practical technology.';

    const groups=[
      ['Software Development','laptop-code',[['Java','75'],['C#','75'],['C++','70'],['Python','70'],['JavaScript','90'],['Node.js','70'],['SQL','85']]],
      ['Modern Web','globe',[['HTML5','95'],['CSS3','90'],['React','75'],['Vite','75'],['Tailwind CSS','70'],['JavaScript','90']]],
      ['Data & Cloud','database',[['MySQL','85'],['Oracle Database','65'],['Firebase','85'],['SQL / Database Systems','85']]],
      ['Tools & Infrastructure','server',[['Git','90'],['GitHub','90'],['VS Code','90'],['Visual Studio','80'],['Linux','70'],['Bash','65'],['Cisco Packet Tracer','85']]],
      ['Networking','network-wired',[['IPv4 & Subnetting','80'],['Routing & Switching','78'],['VLANs','75'],['DHCP & DNS','78'],['WiFi & Mesh Networks','85'],['Network Troubleshooting','85']]],
      ['Security & AI','shield-alt',[['Kali Linux','60'],['Ethical Hacking Fundamentals','55'],['Network Security','65'],['AI / Generative AI','65'],['Automation','60']]]
    ];
    const sg=$('.skills-grid'); if(sg) sg.innerHTML=groups.map((g,i)=>`<div class="skill-category" data-aos="fade-up" data-aos-delay="${Math.min(i*50,250)}"><h3 class="skill-category-title"><i class="fas fa-${g[1]}"></i> ${g[0]}</h3><div class="skill-items">${g[2].map(x=>`<div class="skill-item"><div class="skill-info"><span class="skill-name">${x[0]}</span><span class="skill-percentage">${x[1]}%</span></div><div class="skill-bar"><div class="skill-progress" data-width="${x[1]}"></div></div></div>`).join('')}</div></div>`).join('');

    /* Local images uploaded to Portfolio-Website are used wherever available. */
    const projects=[
      {title:'Centalytics — Hospital Management System',type:'Full Stack · Healthcare',image:'assets/images/hospital.png',alt:'Centalytics hospital management system',description:'Healthcare management platform for patient records, appointments, doctors, visits, prescriptions, laboratory workflows and role-based dashboards.',tech:['HTML5','CSS3','JavaScript','Firebase'],repo:'https://github.com/Dagg12/Centalytics',live:'https://centalytics-cef6c.web.app'},
      {title:'DaggWorld Business OS',type:'Product · Business Systems',image:'assets/images/DaggWorld BOS.png',alt:'DaggWorld Business OS',description:'Business operating system for customers, records, operations, analytics and day-to-day digital workflows.',tech:['React 19','Vite 7','JavaScript','Firebase 12','Node.js','jsPDF'],repo:'https://github.com/Dagg12/daggworld-business-os',live:'https://daggworld-business-toolkit.web.app/'},
      {title:'The Ranger — Safari Management System',type:'ASP.NET · MySQL',image:'https://raw.githubusercontent.com/Dagg12/Ranger-Management-Sytem/master/The%20ranger%20images/landing%20page%20.png',alt:'The Ranger safari management system landing page',description:'Safari/private-reserve management system covering clients, owners, accommodation, game drives, bookings and reporting workflows.',tech:['C#','ASP.NET Web Forms','MySQL','Bootstrap'],repo:'https://github.com/Dagg12/Ranger-Management-Sytem',live:''},
      {title:'THAMAS TECH WORLD — Business Website',type:'Client · ICT & Networking',image:'assets/images/thamas-portfolio.png',alt:'THAMAS TECH WORLD business website',description:'Real-client business website representing ICT, WiFi, computer support, website and technical services.',tech:['HTML5','CSS3','JavaScript','GSAP'],repo:'https://github.com/Dagg12/Thamas-portfolio',live:'https://dagg12.github.io/Thamas-portfolio/'},
      {title:'Nare & Philippine — Fragrance House',type:'Freelance · Client Web',image:'https://raw.githubusercontent.com/Dagg12/Philippine-website/main/dist/products/background-20260906.png',alt:'Nare and Philippine fragrance house website',description:'Premium client fragrance experience with product presentation, responsive UI and a polished brand-focused interface.',tech:['React','Vite','JavaScript','CSS'],repo:'https://github.com/Dagg12/Philippine-website',live:'https://dagg12.github.io/Philippine-website/'},
      {title:'Naledi Nail Studio',type:'Client · Beauty Portfolio',image:'assets/images/Naledi.png',alt:'Naledi Nail Studio nail art portfolio',description:'Client portfolio website for Nails by Naledi, showcasing real nail-art photography, services, pricing, gallery categories and direct WhatsApp booking.',tech:['HTML5','CSS3','JavaScript','GitHub Pages'],repo:'https://github.com/Dagg12/Naledi-Portfolio-',live:'https://dagg12.github.io/Naledi-Portfolio-/'},
      {title:'Clinical Blood Bank System',type:'ASP.NET · Database',image:'assets/images/bloodbank.png',alt:'Clinical Blood Bank system',description:'Blood-bank management application for donor records, blood inventory, hospital requests and stock tracking.',tech:['C#','ASP.NET','MySQL'],repo:'https://github.com/TeeCee07/ClinicalBloodBank',live:''}
    ];
    const pg=$('.projects-grid'); if(pg) pg.innerHTML=projects.map((p,i)=>`<article class="project-card d12-current-project" data-aos="flip-up" data-aos-delay="${Math.min(i*60,300)}"><div class="project-card-inner"><div class="project-image"><img src="${p.image}" alt="${p.alt}" loading="lazy"><div class="project-overlay"><span class="project-type">${p.type}</span></div></div><div class="project-content"><h3 class="project-title">${p.title}</h3><p class="project-description">${p.description}</p><div class="project-tech">${p.tech.map(t=>`<span>${t}</span>`).join('')}</div><div class="project-links"><a href="${p.repo}" target="_blank" rel="noopener noreferrer" class="project-link github-link"><i class="fab fa-github"></i> Code</a>${p.live?`<a href="${p.live}" target="_blank" rel="noopener noreferrer" class="project-link demo-link"><i class="fas fa-external-link-alt"></i> Live Demo</a>`:''}</div></div></div></article>`).join('');

    const timeline=$('#experience .timeline'); if(timeline) timeline.innerHTML=`<div class="timeline-item" data-aos="fade-up"><div class="timeline-dot"><i class="fas fa-laptop-code"></i></div><div class="timeline-content"><div class="timeline-header"><h3 class="timeline-title">Freelance Software Developer & IT Specialist</h3><span class="timeline-date">2024 – Present</span></div><h4 class="timeline-company">Independent Freelance Work</h4><ul class="timeline-list"><li><i class="fas fa-check-circle"></i> Delivered websites and digital systems for real clients.</li><li><i class="fas fa-check-circle"></i> Translated client requirements into practical technology solutions.</li><li><i class="fas fa-check-circle"></i> Built responsive websites and business-focused applications.</li><li><i class="fas fa-check-circle"></i> Provided technical support, troubleshooting and IT consulting.</li></ul></div></div><div class="timeline-item" data-aos="fade-up" data-aos-delay="100"><div class="timeline-dot"><i class="fas fa-network-wired"></i></div><div class="timeline-content"><div class="timeline-header"><h3 class="timeline-title">Co-Founder · Networking & ICT Specialist</h3><span class="timeline-date">2026 – Present</span></div><h4 class="timeline-company"><a href="https://dagg12.github.io/Thamas-portfolio/" target="_blank" rel="noopener noreferrer">THAMAS TECH WORLD <i class="fas fa-external-link-alt"></i></a></h4><ul class="timeline-list"><li><i class="fas fa-check-circle"></i> WiFi installation, configuration, coverage improvement and troubleshooting.</li><li><i class="fas fa-check-circle"></i> Computer repairs and hardware troubleshooting.</li><li><i class="fas fa-check-circle"></i> Website development and digital business support.</li></ul></div></div>`;

    const stats=$$('.stat-number'),labels=$$('.stat-label'); [['10+','Projects Built'],['45+','Technologies & Tools'],['15+','GitHub Repositories'],['Client','Real Client Work']].forEach((x,i)=>{if(stats[i]){stats[i].dataset.count=x[0]==='Client'?'1':parseInt(x[0],10);stats[i].textContent=x[0]}if(labels[i])labels[i].textContent=x[1]});

    if(!$('#daggworld-store')){const s=document.createElement('section');s.id='daggworld-store';s.className='section d12-store-section';s.innerHTML=`<div class="container"><div class="section-header" data-aos="fade-up"><span class="section-tag">DaggWorld</span><h2 class="section-title">Digital <span class="highlight">Store</span></h2><div class="section-divider"></div></div><div class="d12-store-card" data-aos="fade-up"><div class="d12-store-image"><img src="assets/images/Store.png" alt="DaggWorld digital store" loading="lazy"></div><div class="d12-store-copy"><span class="section-tag">DAGGWORLD DIGITAL PRODUCTS</span><h3>Small Business Digital Starter Kit</h3><p>Practical digital resources created to help small businesses get organised, improve their online presence and work more professionally.</p><div class="d12-store-actions"><a class="btn btn-primary" href="https://payhip.com/b/5uo72" target="_blank" rel="noopener noreferrer"><i class="fas fa-store"></i> Visit Store</a><a class="btn btn-outline" href="https://payhip.com/DaggWorld" target="_blank" rel="noopener noreferrer">Explore DaggWorld</a></div></div></div></div>`;$('#contact')?.before(s)}
    const phone=$('#contact a[href^="tel:"]'); if(phone) phone.textContent='+27 67 846 8311';

    const st=document.createElement('style'); st.textContent=`.d12-current-project{min-height:100%}.d12-current-project .project-image img{width:100%;height:100%;min-height:260px;object-fit:cover;object-position:center;display:block}.d12-current-project .project-description{min-height:96px}.d12-current-project .project-tech{display:flex;flex-wrap:wrap;gap:6px}.d12-store-section{position:relative;overflow:hidden}.d12-store-card{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(0,.95fr);gap:34px;align-items:center;padding:28px;border:1px solid rgba(148,163,184,.25);border-radius:28px;background:rgba(15,23,42,.72);backdrop-filter:blur(14px);box-shadow:0 24px 70px rgba(0,0,0,.2)}.d12-store-image{border-radius:20px;overflow:hidden;min-height:280px;background:#0f172a;display:flex;align-items:center;justify-content:center}.d12-store-image img{width:100%;height:100%;min-height:280px;object-fit:cover}.d12-store-copy h3{font-size:clamp(1.7rem,3vw,2.5rem);margin:.65rem 0 1rem}.d12-store-copy p{color:var(--text-secondary,#94a3b8);line-height:1.8}.d12-store-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:22px}@media(max-width:800px){.d12-store-card{grid-template-columns:1fr;padding:18px}.d12-store-image,.d12-store-image img{min-height:220px}.d12-current-project .project-description{min-height:0}}`; document.head.appendChild(st);

    $$('.matrix-background').forEach(canvas=>{const ctx=canvas.getContext('2d');if(!ctx)return;let drops=[];const resize=()=>{const r=canvas.parentElement.getBoundingClientRect();canvas.width=r.width;canvas.height=r.height;drops=Array.from({length:Math.max(1,Math.floor(r.width/18))},()=>Math.random()*-30)};const draw=()=>{ctx.fillStyle='rgba(10,15,26,.08)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='16px monospace';ctx.fillStyle='rgba(37,99,235,.35)';drops.forEach((d,i)=>{ctx.fillText('01<>/{}[]ABCDEFGHIJKLMNOPQRSTUVWXYZ'[Math.floor(Math.random()*34)],i*18,d*18);drops[i]=d+.45;if(d*18>canvas.height&&Math.random()>.97)drops[i]=0});requestAnimationFrame(draw)};resize();draw();addEventListener('resize',resize,{passive:true})});

    const navbar=$('#navbar'),progress=$('#scrollProgress'),top=$('#backToTop'); addEventListener('scroll',()=>{navbar?.classList.toggle('scrolled',scrollY>50);if(progress)progress.style.width=`${Math.min(100,(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight))*100)}%`;top?.classList.toggle('visible',scrollY>400)},{passive:true}); top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
    const hamburger=$('#hamburger'),navLinks=$('#navLinks'); if(hamburger&&navLinks){hamburger.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');hamburger.classList.toggle('active',open);hamburger.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')))}
    const theme=$('#themeToggle'); if(theme){const icon=theme.querySelector('i'),saved=localStorage.getItem('theme')||'dark';document.documentElement.setAttribute('data-theme',saved);if(icon)icon.className=saved==='dark'?'fas fa-sun':'fas fa-moon';theme.addEventListener('click',()=>{const next=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);localStorage.setItem('theme',next);if(icon)icon.className=next==='dark'?'fas fa-sun':'fas fa-moon'})}
    $$('.skill-progress').forEach(bar=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){bar.style.width=(bar.dataset.width||0)+'%';io.disconnect()}}),{threshold:.3});io.observe(bar)});
    stats.forEach(el=>{if(el.textContent==='Client')return;const target=parseInt(el.dataset.count,10);if(!target)return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let n=0;const timer=setInterval(()=>{n+=Math.max(1,Math.ceil(target/40));if(n>=target){n=target;clearInterval(timer)}el.textContent=n+'+'},25);io.disconnect()}}),{threshold:.5});io.observe(el)});
    $$('.nav-link[href^="#"],.scroll-link[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}}));
  });
})();
